### ISSUE TITLE
Add mobile view

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad-user-documentation#111]
## Why?

The need for a dedicated mobile view of Zammad arose from the everchanging life on the go. Even though the desktop application might be responsive enough for small screens, it proved to be too cluttered and was simply not designed primarily for mobile devices.

By limiting the amount of information to only the most important, the new mobile view strives to provide you, the user, more focused window into your daily tasks. All packaged in a touch-friendly and modern design with great user experience, of course!

## What?

Mobile view has some exclusive features:

* Innovative Zammad UX
* Next-level accessibility
* Ready for multi-device usage
* Progressive web app (PWA) support

## What not?

Mobile view is also currently missing some features which are provided by the desktop view:

* Ticket Article Time Accounting
* Ticket Article **Split** Action
* Linked Tickets & Ticket **Link** Action
* Ticket Macros
* Ticket History
* Ticket Create Templates

Additionally, certain features were intentionally ommitted in order to improve the focus on important information:

* Most Management Features (except ticket user and organization management)
* Most Knowledge Base Features (except ticket integration)
* Most User Profile Functions (except avatar and language preferences)

## How?

Zammad now implements a mobile device detection, which results in automatic redirection to mobile view. Even with this mechanism in place it's possible to explicitly switch between the views by using app links:

* _Continue to desktop_ link in mobile view login screen
* _Continue to desktop_ button in mobile view account overview
* _Continue to mobile_ link in desktop view login screen
* _Continue to mobile_ link in desktop view user avatar dropdown menu

Whenever an app link is used, the choice will be remembered by the user's device and the next time the redirection will behave accordingly.

To properly test the new mobile view, try to access your Zammad instance on a mobile device and log into your account. Then, try to do your common daily tasks:

* Manage & use your ticket overviews
* Search for existing records
* Create a new ticket
* Reply in an already existing ticket
* Modify certain ticket attributes
* Modify certain customer attributes
* Modify certain organization attributes

> NOTE: We intentionally do not provide specific instructions and comprehensive documentation for the mobile view! The overall UX should be intuitive and self-explanatory in most cases.

```[tasklist]
### Tasks
- [x] Add mobile view section
- [x] Review
- [ ] Rework screenshots against `demo-chrispresso`
- [ ] Apply findings from review
```
