### ISSUE TITLE
Two-factor authentication (2FA) user features

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad-user-documentation#119]
```[tasklist]
### Tasks
- [x] Document extended **Password & Authentication** section in user profile
- [x] Add a new section for 2FA management
- [x] Explain the security code in the login dialog
- [x] Add a new section for setting up Authenticator App method
- [x] Explain the Try Another Method screen
- [x] Add a new section for setting up Security Keys method
- [x] Extend the base 2FA section to cover Recovery Codes behavior
```

**Comment by dvuckovic** [comment]
We will wait with merging this to pre-release branch until latest is switched to version 6.0.
