### ISSUE TITLE
 Documentation for S/MIME enhancements

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-user-documentation#139]
```[tasklist]
### Tasks
- [ ] S/MIME certificate and private key validation check on upload
- [ ] Support separated and combined certificates for signing/verification and encryption/decryption.
- [ ] Update translation file

```

**Comment by tschaefer** [comment]
@ralf401 Please find the following further information.

### Certificate and private key check on upload

The certificate validation is based on the `X509v3 extensions`. If the extension `Extended Key Usage` is present, it must contain the value `E-mail Protection`. At least one valid email address must be present within the obligatory extension `Subject Alternative Name`. Any email address must be prefixed with `email:` or `rfc822:`. The extension `Key Usage` must be present and contain one or both of the values `Digital Signature` and `Key Encipherment`. The containing public key algorithm must be either `RSA` or `EC`. This also applies to uploaded private keys.

```
$  openssl x509 -in spec/fixtures/files/smime/alice@acme.corp+sign+encrypt.crt -noout -text
...
        Validity
            Not Before: Aug  1 14:20:28 2023 GMT
            Not After : Jul 31 14:20:28 2024 GMT
...
        X509v3 extensions:
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Key Usage:
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Subject Key Identifier:
                74:17:9D:7D:87:C4:1B:C9:7D:04:DD:37:63:C8:22:69:CA:55:FF:46
            X509v3 Authority Key Identifier:
                C2:A7:00:D8:F0:24:BF:E5:6F:57:CF:AB:4A:66:F8:61:78:FF:EF:28
            X509v3 Subject Alternative Name:
                email:alice@acme.corp
            X509v3 Extended Key Usage:
                E-mail Protection
```

In the case of an uploaded CA certificate - the extension `Basic Contstraints` contains the value `CA:TRUE` all the above verification steps are paused.
In general, for outgoing email SMIME security the usage of any expired (`Not After`) or not yet valid (`Not Before`) certificate is denied.

The `Key Usage` is currently not displayed in the admin interface, so no new screenshots are needed.

**Comment by ralf401** [comment]
@tschaefer & @dvuckovic 
I think changes are only in the admin documentation needed. For the "standard" user it is too technical. And for the general zammad documentation it might be too detailed in this "installation" phase. 
I already closed the issue for the user-documentation and would do the same here, as well and focus on the admin-documentation. Do you agree?

**Comment by dvuckovic** [comment]
Makes sense to me, users are not really interested in this "backstory" anyway. As long as they can actually _use_ the feature without any barriers, all is fine.
