### ISSUE TITLE
Extension of glossary

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-user-documentation#234]
```[tasklist]
### Tasks
- [x] Avatar
- [x] Auto response
- [x] Channel
- [x] Custom object attributes
- [x] Merging tickets
- [x] Notifications
- [x] Overview
- [x] Priority (rework)
- [x] State (rework status)
- [x] Reporting
- [x] Signature
- [x] Sidebar
- [x] Splitting tickets
- [x] Scheduler (and automation?)
- [x] Title
- [x] Ticket hook
- [x] Trigger
```
