### ISSUE TITLE
Document the usage of Whatsapp-Channel

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-user-documentation#247]
```[tasklist]
### Tasks
- [x] Prerequisite: setup of channel
- [ ] Explain restrictions (time window for answers, attachments, etc.)
- [ ] Explain usage
- [ ] Check if screenshots can be replaced/added
```

**Comment by dvuckovic** [comment]
Hm, I'm a bit sceptical we would need anything about this channel in the User Documentation. Think about it, we don't have anything about FB or Telegram or other specialized channels. The usage from the user perspective should be intuitive and requires no explanations. For sure, there are some limitations in what can be uploaded by the user within the reply area, but this can be easily checked via trial & error.

I'm also not sure where would this supposed text even go, so I'm inclined to close this issue in favor of admin docs.

**Comment by dominikklein** [comment]
I think this would be something for an Q&A or tutorial in the new documentation?

**Comment by ralf401** [comment]
Yes I totally agree with both of you. I just thought about replacing screenshots to have it visible in the user docs and go through the documentation to see if it makes sense to write some sentences about it. But yes, we don't have it for other channels so I close this issue.
